autoInstallPeers: true
dedupePeerDependents: true
strictPeerDependencies: true
minimumReleaseAgeStrict: true

onlyBuiltDependencies:
  - esbuild

peerDependencyRules:
  allowedVersions:
    "eslint-plugin-react>eslint": "10"

minimumReleaseAgeExclude:
  - happy-dom@20.13.2
